### PR TITLE
Make link text configurable

### PR DESCRIPTION
**Pull request by bondjimbond**
# Github issue #6 

# What does this Pull Request do?

New admin form variable for the link title. Lets admin change the text of the CSV download block.

# Interested parties

@mjordan

### CODE REVIEW

**Comment by mjordan** [comment]
@bondjimbond thanks. Your PR works as intended, but currently the link text is translatable (i.e., wrapped in `t()`). If it becomes an admin variable, it is no longer translatable, as far as I know. Can we look into how to make strings defined as admin variables translatable? If it's not possible, I'll still merge it.

**Comment by mjordan** [comment]
Sorry, you've still got the `t()` there, I'll just merge this as is and we can address translatability later if it becomes an issue.

**Comment by bondjimbond** [comment]
Hmm, looks like translatability is another setting in the form? 

`'translatable' => TRUE;`

https://www.drupal.org/docs/7/creating-custom-modules/making-your-custom-data-translatable

**Comment by mjordan** [comment]
I read that page as meaning that `translatable` applies to string defined by the block, not system settings values. But I could be wrong. I think we'd need to test this with a non-English locale to see if it works.

**Comment by bondjimbond** [comment]
Yeah, I have no idea how to test this. Translatability is not a thing I know much about.

**Pull request merged**
